### ISSUE TITLE
Block Error on Home page Edit 

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#11]
![Screen Shot 2022-07-01 at 11 38 15](https://user-images.githubusercontent.com/39980/176951743-f1361412-c3dd-4e27-bc33-fac16001c49b.png)

I am not quite sure, what's causing it...

**Comment by ryelle** [comment]
Gutenberg was deactivated, and this section uses something that's only available in the plugin. Activating it fixed the issue. also, I looked at the test site, and all the plugins that were active before are now active, including "Subscribers Only" which limits the site to logged in members only - you can deactivate it whenever you're ready.

**Comment by bph** [comment]
Thank you so much! I activated Subscribers only plugin as well, that gives us let trouble.

**Comment by bph** [comment]
I also like that we use the plugin as well, so we dog-fooding latest updates. :-)
