### ISSUE TITLE
Navigation block: Inserter [+] is hardly visible on editing a Submenu

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#12]
It's low contrast with black on blue colore scheme
<img width="242" alt="Screen Shot 2022-08-11 at 15 39 58" src="https://user-images.githubusercontent.com/39980/184147049-e2f5627e-68c8-484a-ac7d-913cde683f0c.png">

**Comment by ryelle** [comment]
@bph I think this is a gutenberg issue — I see the same issue on TT2

<img width="284" alt="Screen Shot 2022-08-11 at 11 52 03 AM" src="https://user-images.githubusercontent.com/541093/184175940-3a9f990c-f115-4807-8903-41993055f92f.png">

**Comment by bph** [comment]
Ah, thanks for checking it. Let's close the issue for now and research it upstream
