### ISSUE TITLE
Commercial Link on developer.wordpress.org content

### ISSUE THREAD

**Issue by AndrewJDFerguson** [WordPress/wporg-developer-blog#13]
Not sure if this is the correct place to add this issue, but neither is having a commercial link buried in content on the developer.wordpress.org.

If you view https://developer.wordpress.org/themes/basics/template-hierarchy/#visual-overview you will notice a link "You can also [interact with this diagram](http://wphierarchy.com/)." The link is to wphierarchy.com, and following that link ultimately takes you to [https://wpshout.com/wordpress-template-hierarchy/](https://wpshout.com/wordpress-template-hierarchy/). WPShout appears to be all about getting you to sign up for their paid course, and while there may be some content relevant to the content on the developer.wordpress.org page, it is, in my view, of very little value. 

Should this link be there? I think not. 

![Commercial-Link](https://user-images.githubusercontent.com/37160315/193088829-e6faca8f-b080-4651-bff6-92424ba4426e.png)

**Comment by bph** [comment]
This repo is only dealing with the Theme development for the Developer blog (soon to be opened)
@AndrewJDFerguson  I used above information and [placed it on the Documentation team's Issue tracking space. ](https://github.com/WordPress/Documentation-Issue-Tracker/issues/562)
