### ISSUE TITLE
The site editor doesn't have a top left link 

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#16]
When I am in the site editor adjusting the front page template, there is no black W that would bring me back to the dashboard etc. 
![Screen Shot 2022-11-17 at 11 15 18](https://user-images.githubusercontent.com/39980/202560935-82b7414c-a31f-4838-9350-f2b880f4740a.png)
Here is also a video on the reload. It shows briefly the "Toggle Navigation" tool tip but there is not link to be clicked. 
http://recordit.co/lDPxpL6uQ2

**Comment by bph** [comment]
Seems, I am also not able to reach the other templates, like single post and single page. 
For instance, I'd like to list the categories and the tags on a post. If that something you need to do, @ryelle, please let me know, and I create a follow-up issue.  😄

**Comment by bph** [comment]
In the meantime, I am able to browse the template through the Top drop down via the Browse all Templates button
[Or via this link ](https://developer.wordpress.org/news/wp-admin/site-editor.php?postType=wp_template)

**Comment by ryelle** [comment]
It looks like this link is back now, though the (w) is dark on dark. @bph Can you access the button now?

<img width="367" alt="Screenshot 2023-01-06 at 11 59 03 AM" src="https://user-images.githubusercontent.com/541093/211060413-66e30d71-ccc9-4b09-bbcc-eadd8d6163ef.png">

**Comment by bph** [comment]
Yes, I see it now. Thank you.
