### ISSUE TITLE
Latest Post 

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#20]
cc: @javierarce  @jasmussen

The entries of the Latest post section should use the same design they have in News. That means removing the Read more link and the bold style for the date.
![Screen Shot 2022-11-21 at 09 31 24](https://user-images.githubusercontent.com/39980/203080595-763296f5-a6e2-4cdc-b87b-fe090625366c.png)

The grid and design for the blog is different from /news. 

News:
![Screen Shot 2022-11-21 at 09 41 20](https://user-images.githubusercontent.com/39980/203083022-7414efb7-181a-4e69-ab05-be5d9e9dad84.png)

Dev blog
![Screen Shot 2022-11-21 at 09 41 26](https://user-images.githubusercontent.com/39980/203082934-be26d1a6-0da9-49ae-b33d-e5928949308e.png)
Can’t the main blog features be identical to that of /news?

- [x] remove Read more
- [x] Add categories
- [x] unbold date 
- [x] add spacing between posts
- [x] update grid design (ratio between left and right column)

**Comment by bph** [comment]
![Screen Shot 2022-11-28 at 14 25 57](https://user-images.githubusercontent.com/39980/204363658-778c2267-f8a0-463d-93c2-7efb89def438.png)

Four of five to-do- items are fixed. 

I don't know how to update the ratio between the left and the right column, though.l

**Comment by jasmussen** [comment]
A question for perhaps @ryelle or @StevenDufresne, how come the developer blog looks so different from /news, if it's using the same theme? Ideally it should be the same without having to do anything, right?

**Comment by ryelle** [comment]
@jasmussen It's not using the News theme, News has a lot of hardcoded content in it and doesn't actually work in the site editor (so we can't just locally overwrite templates). It's not reusable, think of that theme as more of a very well done prototype, it's unrelated code-wise to the other redesigned sites.

This site is using the `wporg-parent-2021` theme, same as the other new designed pages (wporg, showcase, documentation, etc), with a child theme [here in this repo](https://github.com/WordPress/wporg-developer-blog/tree/trunk/source/wp-content/themes/wporg-developer-blog). The parent theme is a stripped back version of News, without a lot of the custom HTML & CSS. Instead, the focus of the parent theme is making sure we can use the site editor. Unfortunately, this & issue #23 are prime examples of custom HTML & CSS that doesn't support the block editor :/

<img width="1159" alt="Screenshot 2022-11-29 at 10 55 25 AM" src="https://user-images.githubusercontent.com/541093/204578398-711c2bfd-e719-4b2f-a378-db5f65ef261a.png">

> I don't know how to update the ratio between the left and the right column, though.

The ratio here matches [the category archives](https://wordpress.org/news/category/interviews/), not the homepage. I did some manual tweaking to the template and got it a lot closer to how that middle section of News looks, though.

![Screen Shot 2022-11-29 at 11 12 14](https://user-images.githubusercontent.com/541093/204582488-3ac8075d-d864-4b20-b8b9-3f09e5d9c972.png)

**Comment by bph** [comment]
Thank you so much, @ryelle for taking another look at this and fix it so fast. This resolved the Latest post display.
