### ISSUE TITLE
Secondary content boxes

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#23]
These two widget areas look a bit unrefined: 
![Screen Shot 2022-11-21 at 09 43 42](https://user-images.githubusercontent.com/39980/203083584-101411a0-872b-429e-8bb5-7dc6192841e2.png)
Text could use the same font size, and post meta could be unified on a single row, like /news:
![Screen Shot 2022-11-21 at 09 44 46](https://user-images.githubusercontent.com/39980/203083712-c18abe19-d97f-4782-aa66-9b1c5e64874f.png)
The “Bold” for “calendar of online workshops” tips the balance a little bit compared to the other items. If it’s an important piece on its own, there might be an opportunity to reuse the row+columns pattern from /news, and give this item its own box entirely, a la this:
![news slots](https://user-images.githubusercontent.com/39980/203083882-5c6723ad-8ebd-49c1-b70a-79481078c9e3.gif)
In such a case, the newsletter could also be part of it, and sit on a white background.

cc: @javierarce  @jasmussen

**Comment by bph** [comment]
It seems the "reuse the row+columns pattern from /news" is not a block pattern that's available via the Site Editor. It will need a developer to implement.

**Comment by jasmussen** [comment]
Does /news use the site editor to build the whole thing?

**Comment by ryelle** [comment]
> Does /news use the site editor to build the whole thing?

I think we talked about this elsewhere back when this was posted, but for reference — no, a lot of news was hardcoded in HTML files, and it doesn't work well with the site editor. This "pattern" in particular is custom to News.

We can create a multiple column layout, but as far as I know there are no GB-native ways to change the column layout like News does.

**Comment by jasmussen** [comment]
> We can create a multiple column layout, but as far as I know there are no GB-native ways to change the column layout like News does.

What can we do to make this transferrable? Much of /news was intentionally designed to be reused in contexts like these.

**Comment by ryelle** [comment]
Add them to the Design Library figma and/or create an issue on [wporg-parent-2021](https://github.com/WordPress/wporg-parent-2021/) and we'll get them into the parent theme as reusable patterns.

**Comment by ndiego** [comment]
This can be closed now that the redesign is complete. See https://github.com/WordPress/wporg-developer-blog/issues/46.
