### ISSUE TITLE
New Beta  Banner

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#27]
Let’s make the beta banner similar to the language bar but in yellow. Right now, the link is invisible. And I think we could improve the copy a bit.
![Screen Shot 2022-11-21 at 09 57 12](https://user-images.githubusercontent.com/39980/203086471-dd5daac8-92b4-43e9-b6fd-717455469df1.png)

cc: @javierarce  @jasmussen

**Comment by bph** [comment]
I made some tweaks... however I don't get the yellow bar to span the whole site. 
![Screen Shot 2022-11-28 at 14 13 48](https://user-images.githubusercontent.com/39980/204361920-1f56b7f2-185b-48ba-af34-14451fa03854.png)


I added some numbers in the layout section of the Group block.
 
![Screen Shot 2022-11-28 at 14 14 48](https://user-images.githubusercontent.com/39980/204361792-0783c364-53c1-4dfe-ac68-a70900b85897.png)

**Comment by ryelle** [comment]
> however I don't get the yellow bar to span the whole site.

If you turn off the "Inner blocks use content width" the yellow background paragraph spans the whole section. Or you could have moved the yellow background to the group itself.

I updated the banner & added a little extra spacing.

**Comment by bph** [comment]
Thanks so much for taking a quick look.  That works!

**Comment by bph** [comment]
Opened this issue again, as the "beta banner" only shows on the front page, and needs to be moved into the page/post header template.

**Comment by ryelle** [comment]
@bph I've moved the banner into the cover template part, it should appear on all pages now ✅
