### ISSUE TITLE
Second level navigation white on white

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#3]
When adding a submenu to the navigation block, in the editor, the text is rendered on white background.  It displays fine on the front end. 
<img width="399" alt="Screen Shot 2022-05-25 at 14 59 13" src="https://user-images.githubusercontent.com/39980/170281751-0853be29-3e48-4d2e-9442-bfc9d94d9993.png">
<img width="522" alt="Screen Shot 2022-05-25 at 14 59 38" src="https://user-images.githubusercontent.com/39980/170281775-34b3fcf9-5252-4ff7-871c-54100d6fcd91.png">

Frontend works fine
<img width="436" alt="Screen Shot 2022-05-25 at 15 06 29" src="https://user-images.githubusercontent.com/39980/170281866-442c3b49-1c65-4d45-8082-40a97a3513e6.png">

**Comment by ryelle** [comment]
I've updated the template to add a nav menu banner, does this work?

![theme](https://user-images.githubusercontent.com/541093/170542267-3289bce3-4de6-42c7-883c-282ef1e4841f.png)

![editor](https://user-images.githubusercontent.com/541093/170542262-664af02c-d2e0-485e-9682-7f9a83e8ded2.png)

**Comment by bph** [comment]
That works well. Thank
