### ISSUE TITLE
Add "All Articles" page and link from front page. 

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#32]
To be somewhat consistent with the .org/news site, we’d want to create an “All Posts” page like so: https://wordpress.org/news/all-posts/
There’s also a “See All Posts” link at the bottom left of the latest posts section: https://wordpress.org/news/ (kind of tough to spot). 

Front page also needs a section with a list of all categories for discovery.

**Comment by bph** [comment]
cc: @justintadlock  @mburridge

**Comment by bph** [comment]
Created an All Posts page with list of headlines, metadata and pagination. 
![AllPost-Page-w-pagination](https://user-images.githubusercontent.com/39980/205753148-84f8b258-a5ac-4715-a28d-55edc21eb752.png)

- The space between pieces of meta data is a little off. In the editor, the author name is not aligned. 
- The space between post headline could be smaller
- The left site looks a bit empty. Is there a template that could be used? 
What else? 
[Public preview is enabled](https://developer.wordpress.org/news/?page_id=348&preview=1&_ppp=d50a1504b0)

**Comment by bph** [comment]
View of how the post metadata align in the editor. 
<img width="563" alt="Screenshot 2022-12-05 at 5 12 49 PM" src="https://user-images.githubusercontent.com/39980/205753762-0cc75baf-66db-453a-9399-02adecb3feaf.png">

**Comment by ryelle** [comment]
I've added a new template (All Posts) and tweaked [the content in this page](https://developer.wordpress.org/news/wp-admin/post.php?post=348&action=edit), so now this looks like this:

![Screen Shot 2023-01-06 at 12 51 53](https://user-images.githubusercontent.com/541093/211069934-3d02bee1-8661-4489-abc6-6ae7f6813ccf.png)

It could still use some CSS to fix up the meta and some of the other issues.

**Comment by bph** [comment]
Thank you. It is certainly a big improvement

[Page is  in public preview](https://developer.wordpress.org/news/?page_id=348&preview=1&_ppp=b8748ed47f)

**Comment by bph** [comment]
I just took the [All Posts page](https://developer.wordpress.org/news/all-posts/) live with a _See all posts_ link from the front page
