### ISSUE TITLE
Make menu bar "sticky"

### ISSUE THREAD

**Issue by mburridge** [WordPress/wporg-developer-blog#36]
Given the length of some of the posts, and the fact that comment threads could be of arbitrary length, it would be really nice if the blog menu bar could be made ‘sticky’, i.e. stick just below the main site menu bar at the top of the page on scroll.

![image](https://user-images.githubusercontent.com/20643925/221246064-f342b3cf-6ddc-4f4a-9729-a58a6d874510.png)

![image](https://user-images.githubusercontent.com/20643925/221247503-a6f37469-ec7a-40e2-a142-3855734e6a56.png)

**Comment by ndiego** [comment]
This can be closed now that the redesign is complete. See https://github.com/WordPress/wporg-developer-blog/issues/46
