### ISSUE TITLE
Tags and Comments on "Center columns" template not centered

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#38]
We have switch using the Center column template for all out posts, 
I added Tags to the bottom of the content as well as the comments section. 

It all works well, except both neither the tags of the columns stay in the center of the browser window like the post content does. 

Example post [What’s new for developers? (March 2023)](https://developer.wordpress.org/news/2023/03/whats-new-for-developers-march-2023/)
**Here is a video:**

https://user-images.githubusercontent.com/39980/225087190-50a984b1-cbb7-4ac7-b0d1-4536d6bb4068.mp4

@renintw When you have a moment to let me know how I can make the display consistent with post content.

**Comment by justintadlock** [comment]
I have updated the Centered Column template so that the tags and comments sections are in line with the content section. I'll leave this ticket open for further feedback from @bph in case I missed anything. Otherwise, it can be closed.

**Comment by outdoor2kode** [comment]
Thanks @justintadlock. I tested a few more posts and it looks good to me now.

**Comment by bph** [comment]
Yes, this is now all working nicely. I added some padding left and right to the Post title group block for mobile views. Thanks @justintadlock, I closed the issue.
