### ISSUE TITLE
Add "note" and "warning" block style variations

### ISSUE THREAD

**Issue by justintadlock** [WordPress/wporg-developer-blog#40]
Currently, there is no standard block styles for providing notes or warnings. We must manually add colors and padding. The issue with this is that each writer would have to remember the exact styles to choose, and these color names could potentially change in some future update. But, if we add a couple of block style variations to the Group and Paragraph blocks, it'd be easy to keep this consistent.

I've been using the Blueberry 4 background color, Black text color, and Small padding size to accomplish this for "notes" but haven't had a need for "warnings" yet (both would be pretty common styles for developer blog posts):

<img width="1374" alt="dev-blog-highlights" src="https://user-images.githubusercontent.com/1816309/234042550-3bd8fd20-a940-4f4c-8d0c-45ae4985ee47.png">

**Comment by ryanwelcher** [comment]
Big +1 from me. It's a big timesaver.

**Comment by ryelle** [comment]
Would the Notice block work for this? It's got 4 variations (tip, info, alert, warning) and is styled using the redesign colors:

<img width="782" alt="Screenshot 2023-04-24 at 12 20 06 PM" src="https://user-images.githubusercontent.com/541093/234056853-5f4ca3f6-1e55-457d-b48f-6157002aec0b.png">

The only difference is it includes an icon.

**Comment by justintadlock** [comment]
TIL: We have a Notice block.  

That should work great! The only potential downsides are that it looks like you can't quickly transform a Paragraph into a Notice and doesn't support nested blocks. I'll go ahead and close this because it handles the base use case.
