### ISSUE TITLE
Link previews are not showing up on LinkedIn

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer-blog#41]
I recently shared [this link](https://developer.wordpress.org/news/2023/05/curating-the-editor-experience-with-client-side-filters/) on both Twitter and LinkedIn. The Twitter link appeared as expected with a featured image, title, and excerpt. However, on LinkedIn, the link just returns the overall site description. 

| LinkedIn      | Twitter |
| ----------- | ----------- |
| ![image](https://github.com/WordPress/wporg-developer-blog/assets/4832319/d0228137-7d6b-4c90-90fb-1800672430ea)      | <img width="619" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/f8b11f31-121f-4183-bef6-15bf9b36272c">       |

**Comment by bph** [comment]
Similarity, we posted the What's new for Developers post to Facebook and no featured.image was displayed. 
![Screenshot_20230601-072223](https://github.com/WordPress/wporg-developer-blog/assets/39980/40fce87f-1b1f-4008-88be-9a8361c3f3eb)

**Comment by ryelle** [comment]
It looks like the social image generator plugin is putting the `og:image` into the page too late, under all the inlined CSS. Facebook only looks up to a certain point in the document, and so it's functionally hidden by the CSS. I don't see a way to force the social image generator to output earlier, but maybe the CSS can be output later.

Maybe when we can switch from the Social Image Generator plugin to the version in Jetpack, we'll have more control over the output. Or if not, at least we can report it back to Jetpack :)

**Comment by ndiego** [comment]
Hmm, interesting. I was just looking at my own site and Yoast seems to be able to do it. 

<img width="1601" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/8f914fe4-293d-4091-9fb1-6cedd4567b79">

**Comment by ryelle** [comment]
Yeah, it looks like Yoast attaches to `wp_head` with priority 1, so it outputs first. The social image generator uses the default priority, so it ends up after all the CSS.

**Comment by bph** [comment]
Doesn't Jetpack also integrated the Socail Image Generator? Maybe we would need to use the tools from there? 
Here are the screenshots from the three socail networks, sharing the [What's New for Developers (June 2023)](https://developer.wordpress.org/news/2023/06/whats-new-for-developers-june-2023/) post. 
You'll see only the Facebook one doesn't show the auto-generated featured image and doesn't pick up the title. It did pick up the excerpt, though. 

## Twitter 
<img width="601" alt="Screenshot 2023-07-05 at 15 08 24" src="https://github.com/WordPress/wporg-developer-blog/assets/39980/d3d7d820-b437-4f81-b291-8fc9452c3234">

## LinkedIn
<img width="506" alt="Screenshot 2023-07-04 at 17 20 24" src="https://github.com/WordPress/wporg-developer-blog/assets/39980/e08f6922-c5d6-4379-8049-816fd7230061">

## Facebook 
<img width="716" alt="Screenshot 2023-07-05 at 15 03 18" src="https://github.com/WordPress/wporg-developer-blog/assets/39980/8d901e82-5933-4767-83ee-a4fee488a16a">

**Comment by ryelle** [comment]
> Doesn't Jetpack also integrated the Socail Image Generator? Maybe we would need to use the tools from there?

When I posted my comment, I think the social image generator in Jetpack wasn't released yet. If it's out now, you could give that a try - it might use an earlier priority (or they might be more open to fixing it).

**Comment by justintadlock** [comment]
We're now missing the `og:image` field altogether in `<head>`, so we're not getting social images on places like Twitter either. I'm wondering if that's a recent change with Jetpack or the other plugin??

I don't have access to Jetpack settings on the Dev Blog to check.

**Comment by bph** [comment]
@ryelle 

Neither @justintadlock nor I have  access to the Jetpack settings.  

What is entirely missing is this section (copied from the make core blog)

<img width="1378" alt="Screenshot 2023-07-12 at 13 20 45" src="https://github.com/WordPress/wporg-developer-blog/assets/39980/fc3ee83d-d66e-4642-be62-47de84fdb21c">

And maybe the Jetpack module that integrates the Social Image generator can be enabled as well. Then we could remove the older plugin.

**Comment by ryelle** [comment]
It looks like the image generator [got swapped out for Jetpack Social](https://meta.trac.wordpress.org/ticket/7110), which needs some setup. I'll try to get this connected later today.

**Comment by ryelle** [comment]
Okay, I've activated Jetpack Social and added the plan for the image generator. Unfortunately, it seems you need to manually enable it on each post. I quickly configured it for the latest post, so here's what that one looks like now:

<img width="570" alt="Screenshot 2023-07-12 at 4 22 34 PM" src="https://github.com/WordPress/wporg-developer-blog/assets/541093/b62e20d3-c75a-4351-95c0-e283d0985f4d">

… and I've just noticed the title and excerpt are overly generic. I think that's due to [this code](https://github.com/WordPress/wporg-developer-blog/blob/72b72edfc0cf3892472ab9fa0daf8a0adac6096e/source/wp-content/themes/wporg-developer-blog/functions.php#L50), which we shouldn't need anymore with Jetpack controlling the open graph tags.

**Comment by ryelle** [comment]
Okay, I pushed a commit to fix it, and it looks good now:

<img width="548" alt="Screenshot 2023-07-12 at 4 38 54 PM" src="https://github.com/WordPress/wporg-developer-blog/assets/541093/f5a3260c-7781-45fc-931e-82b1070c2706">

**Comment by bph** [comment]
@ryelle Thank you so much for digging in and fixing the open graph situation. 

Is there a way to at least get the original template back? 

I know I need to ask that in Jetpack social channel, but what is the sense in having a social image generator when it doesn't do it automatically. :-) 
<sigh/>  

Well, I guess I have another items on my list to document for the writers... :-)

**Comment by ryelle** [comment]
Yeah, I think any questions about how to use this would be best asked to Jetpack folks directly, that's really all I would be doing anyway :)

I'm going to close this issue, if it turns out we need to do something else to configure this in the code you can open a new one.
