### ISSUE TITLE
Content images are larger than content width.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer-blog#49]
While viewing [Extending plugins using custom SlotFills](https://developer.wordpress.org/news/2023/12/22/extending-plugins-using-custom-slotfills/), images are unpredictably wider than the content. 

## Screenshot

![developer wordpress org_news_2023_12_22_extending-plugins-using-custom-slotfills_](https://github.com/WordPress/wporg-developer-blog/assets/1657336/c0489d1b-9871-4ff4-b186-a90bfdcae617)

**Comment by ndiego** [comment]
These images were manually set to `alignwide`, so I think this can be considered a content issue.

**Comment by ndiego** [comment]
> These images were manually set to alignwide, so I think this can be considered a content issue.

Closing this since it's a content issue.
