### ISSUE TITLE
Table block doesn't have top margin in editor

### ISSUE THREAD

**Issue by justintadlock** [WordPress/wporg-developer-blog#50]
Using a Table block, it doesn't have any top margin in the editor:

![image](https://github.com/WordPress/wporg-developer-blog/assets/1816309/d139e342-2831-42bf-ae1e-17bc813948b5)

It has margin on the front end.

**Comment by ndiego** [comment]
This issue seems to have fixed itself. Can you confirm @justintadlock?

<img width="898" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/267fab3e-343c-4aaa-90c4-5233eeaa3534">

**Comment by justintadlock** [comment]
Yep, I can confirm it now works. So closing this.
