### ISSUE TITLE
Extra "By" in byline: "By By Author Name"

### ISSUE THREAD

**Issue by justintadlock** [WordPress/wporg-developer-blog#52]
There's an extra "By" in the post bylines on the site. It appears to me like one of them is being automatically injected inside of the Post Author Name block and the other is a plain text one inside of the Paragraph block before it:

![image](https://github.com/WordPress/wporg-developer-blog/assets/1816309/53a802e1-895e-47d0-a5ab-2ac1b841bd28)

**Comment by ryelle** [comment]
This should have been fixed by [this commit](https://github.com/WordPress/wporg-developer-blog/commit/892a6d83a92709059da701ebda117eebe609459a), is it possible that's a custom template & didn't get the update?

**Comment by justintadlock** [comment]
Yes, it looks like it's a custom template. I'm not sure what all is different for it in comparison to the default All Posts template.

**Comment by ryelle** [comment]
I've cleared the customization from the Front Page template — this fixed the double "by", and the content looks the same, so I think it's all good now. If there is something on that page that needs to be updated, open a new issue and we'll make the change in the templates.

**Comment by ndiego** [comment]
The Search template also needed to be cleared, but I took care of that. Should be all set now. Thanks @ryelle
