### ISSUE TITLE
Add Open Graph tags using code instead of Jetpack

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer-blog#53]
There have been some issues recently with Jetpack Social, the tool that automatically added Open Graph tags to posts on the [Developer Blog](https://developer.wordpress.org/news/). While we ultimately need to identify the root of the issue, I think we should manually add the Open Graph tags via code for the time being. 

At a minimum, the following should be added: 

| tag | content |
|-|-|
| `og:title` | post title |
| `og:description` | post excerpt |
| `og:url` | post URL |
| `og:image` | post featured image |

**Comment by justintadlock** [comment]
Agreed. Each of those fields looks good.

**Comment by justintadlock** [comment]
Maybe relevant information for the longer term: It looks like Jetpack Social v4.1.0 was released on 2024-03-07 and is likely the release where things broke.

I can confirm that this was previously working with a post that I published on 2024-03-06.

**Comment by ryelle** [comment]
What image would you want on the homepage? Archive pages?

I could use the main developer.w.org's fallback: https://developer.wordpress.org/wp-content/themes/wporg-developer-2023/images/opengraph-image.png

**Comment by ndiego** [comment]
> What image would you want on the homepage? Archive pages?

@WordPress/meta-design what do you think of this for a default Open Graph image for the Developer Blog?

![Developers social-image](https://github.com/WordPress/wporg-developer-blog/assets/4832319/13de675e-af0a-4eb5-a9ea-e1b07970c54a)

[Figma file is here](https://www.figma.com/file/2CKNK5sN7PKNXA4VjVhyqA/Dev-blog?type=design&node-id=1718-1500&mode=design&t=MS4cVZ3xjANh1rup-0).

**Comment by ndiego** [comment]
@justintadlock what do you think of the above default Open Graph image for the Developer Blog?

**Comment by justintadlock** [comment]
> @justintadlock what do you think of the above default Open Graph image for the Developer Blog?

Looks good to me.

**Comment by ndiego** [comment]
> Looks good to me.

Great, thanks. @ryelle let's move forward with the above as the default image for the homepage, archive pages, etc. Thanks!

**Comment by ryelle** [comment]
will do! I'll update [the PR](https://github.com/WordPress/wporg-developer-blog/pull/54) shortly.

**Comment by bph** [comment]
Shouldn't it be 
`twitter:card = summary_large_image`
