### ISSUE TITLE
Add a "Subscribe" landing page

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer-blog#55]
The Developer Blog currently has less than 1,000 subscribers, and we need to do more to boost this number. In addition to creating more CTAs throughout the site, having a landing page would be very helpful. With something like `developer.wordpress.org/news/subscribe`, you could easily link folks to the page from external sources like social media. 

The page could be quite simple: 

- Heading with primary CTA
- Short paragraph of text explaining the type of content the blog offers
- Jetpack subscribe block

**Comment by justintadlock** [comment]
Agreed, and simple Subscribe page would be a good start. Let's work on some copy this week.

I'd also like to see a link to either the page or a jump link to the form in the navigation menu.

**Comment by bph** [comment]
Good idea. Go for it. 
It felt a bit awkward when I [tweeted](https://twitter.com/bph/status/1767904695064957358) "WordPress Developer Blog with almost weekly new posts. Don't ever miss the new articles and subscribe on the bottom of the homepage" A direct link to a subscribe page would work so much better. 

And  I agree  with @justintadlock having a button in the main navigation would be helpful. 

Definitely needs a featured image as well, to be pulled for the social webs. 

Once the page is in play we could collect variations of social copy for scheduled posts via Social Sprout.

**Comment by ndiego** [comment]
> Definitely needs a featured image as well, to be pulled for the social webs.
>
> Once the page is in play we could collect variations of social copy for scheduled posts via Social Sprout.

Great ideas!

**Comment by ndiego** [comment]
I took a first pass at the page here: https://developer.wordpress.org/news/?page_id=1978&preview=1&_ppp=9c8419337a

| Desktop | Mobile |
|-|-|
|<img width="1374" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/61ed626c-2c9a-4a16-bb26-5555409f9653">|<img width="348" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/7490b113-6dad-4f8e-ab70-f768704c65c0">|


Those with access to the site can find the page "Subscribe" under drafts. The "dots" were inspired by the [Showcase design](https://wordpress.org/showcase/submit-a-wordpress-site/).

**Comment by bph** [comment]
I would add a note about the frequency, that we have mostly 1 or 2 posts per week so people can gauge how much noise they want. 

The headline is a bit unspecific: "Subscribe via email and stay on top of WordPress developer news" or so, might make it clear what this page gives you and I move the subscribe section higher. 

I am not a fan of the dots... sorry.

**Comment by ndiego** [comment]
> I would add a note about the frequency, that we have mostly 1 or 2 posts per week so people can gauge how much noise they want.
> 
> The headline is a bit unspecific: "Subscribe via email and stay on top of WordPress developer news" or so, might make it clear what this page gives you and I move the subscribe section higher.
> 
> I am not a fan of the dots... sorry.

Here's an updated version. Let me know what you think. 

<img width="1432" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/6d8c1a1e-8051-44b9-939e-267f70ed24ad">

**Comment by ndiego** [comment]
Here is a sample thumbnail in the same style as the default site thumbnail. Thoughts?

| Site Default | Subscribe |
|-|-|
|![Developers social-image](https://github.com/WordPress/wporg-developer-blog/assets/4832319/88cb0749-4f5f-45f2-a6e2-fab4283b69d7)|![Developers social-image (1)](https://github.com/WordPress/wporg-developer-blog/assets/4832319/22765329-f56b-485f-a24b-55be28b69b62)|

**Comment by justintadlock** [comment]
✅  Copy
✅  Featured Image

Looks good to me.

I liked the dots as they added a bit more contrast and denoted this as being more of a specialized page by giving it some visual _oomph_. But either direction is fine.

**Comment by bph** [comment]
Awesome! Love the featured image, too.   I say 🚢

**Comment by ndiego** [comment]
Thanks everyone, the page is now live: https://developer.wordpress.org/news/subscribe/
