### ISSUE TITLE
Add a link on the homepage for the monthly roundups

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer-blog#56]
The monthly "What's new for developers?" article is pinned to the top of the Blog, but there is currently no easy way to view past monthly roundups. Each article has the tag `roundup`, but this is not very discoverable. 

I think we should add a simple link to the pinned section that links to the [tag archive](https://developer.wordpress.org/news/tag/roundup/) for `roundup`. We could keep the same design that is used for the other Query loop templates and just display the tag. But other suggestions welcome.

| Current | Updated |
|-|-|
|<img width="878" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/f282d2ca-c866-41e0-bcb7-84dca05e2bb1">|<img width="840" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/e5552814-5949-48b3-b6be-a0d18297f0c3">|

**Comment by justintadlock** [comment]
I think the proposed change would be the easiest way to accomplish this.

I am left wondering (beyond this ticket) if we should have a clearer tag named "What's New for Developers?". I don't think we had this clearly mapped out in the early days, and "roundup" can be used for other types of roundup posts too.

**Comment by ndiego** [comment]
> I am left wondering (beyond this ticket) if we should have a clearer tag named "What's New for Developers?". I don't think we had this clearly mapped out in the early days, and "roundup" can be used for other types of roundup posts too.

Yeah, we could just create a new category specifically for these posts that is more descriptive. They have become a "thing" and deserve to stand out a bit IMO.

**Comment by bph** [comment]
Totally for the link to the tag archive from the sticky post. I could see that a more descriptive excerpt, that for instance mentions the highlighted items would help readers to orient themselves when catching um on previous issues. 
Another idea would be to add the three most important items to the title, that would peak people's interest. Similar to the GT weekend editions...

**Comment by ndiego** [comment]
> that for instance mentions the highlighted items would help readers to orient themselves when catching um on previous issues.

Great idea

**Comment by ndiego** [comment]
What if we update the tag name from `Roundup` to `Monthly Roundups`, and then also ensure the excerpts are a bit more descriptive? I think adding "Monthly" to the tag name provides better context that this tag archive includes all the roundups from previous months. Thoughts?
