### ISSUE TITLE
Add a Subscribe link/button to top navigation

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#60]
I did some experimenting with the navigation to add a subscribe link there. 

## Option 1 as a button. 
![Screenshot 2024-03-16 at 10 29 18](https://github.com/WordPress/wporg-developer-blog/assets/39980/dc21703c-9bfd-4d4d-807a-018dff53d58e)

## Option 2 as a link

![Screenshot 2024-03-16 at 10 30 12](https://github.com/WordPress/wporg-developer-blog/assets/39980/974ce188-7d2e-4a3b-9bdb-e42ff3177644)

What other options / ideas do you have? 
@ndiego @justintadlock

**Comment by justintadlock** [comment]
Yes, @ndiego, agreed that we should add this in the header.

**Comment by ndiego** [comment]
Yeah agreed, I would just add this as a simple link (option 2). We can go ahead and make this change manually. The Navigation menu is stored in the database, not in any theme templates.

**Comment by ndiego** [comment]
All set. Let me know if you would like to see any changes. 

<img width="569" alt="image" src="https://github.com/WordPress/wporg-developer-blog/assets/4832319/de4e804f-a6b4-45a8-9814-8c291c306223">

**Comment by bph** [comment]
Thank you!
