### ISSUE TITLE
[WIP] Add CPT and Fields for Developer Hours posts

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#68]
During [July meeting of the Editorial Group](https://make.wordpress.org/core/2024/07/05/developer-blog-editorial-meeting-summary-july-4-2024/) a [proposal to add Developer Hours recordings](https://github.com/WordPress/developer-blog-content/discussions/277) as posts to the Developer Blog was approved with the following implementation outline

- Create a new Custom Post Type with single post and archive page templates and add them to the normal post feed.
- Each Developer hours will get its individual page with YouTube video embed, shared resources posted and transcript added + Featured image, that is used for the Archive page.
- The Archive page lists each post with title, features image and date.
- As author we would use the main presenter's name.

In this issue and comments, I would like to kick off the discussion for how we approach the implementation.

**Comment by ryanwelcher** [comment]
I'll take this on @bph.

I'll create a plugin like we did for Snippets with the following:

* Developer Hours CPT that supports author, featured image, has an archive and is exposed to the REST API
* Adds CPT to main query and main RSS feed
* Prefixes the title with "Developer Hours:
* New posts start with the following template: YouTube embed block, list block, heading block with "Transcript" preset, paragraph block with "Add transcript" placeholder. Props block?

**Comment by bph** [comment]
Thank you so much @ryanwelcher for taking it on! That looks pretty complete. 
@ndiego Do we need/want/ any additional taxonomy people might need to filter things? or would 'Categories' be enough?

**Comment by ryanwelcher** [comment]
One thought is that we make the CPT more abstract i.e "videos" and use the taxonomy to define it as 'Developer Hours' etc.

This would make it easer to add new types of video content.

**Comment by bph** [comment]
Good thinking. 

that eliminates the prefix, which is ok as we can always add it manually

**Comment by justintadlock** [comment]
Keeping it to the more abstract "videos" makes sense.

I'd probably avoid a people taxonomy for now. Maybe we can tag specific user accounts instead with `@username` in the props section or something similar. Then, down the road, it's very possible to create archives by specific usernames if we ever wanted to do that.

**Comment by ndiego** [comment]
> @ndiego Do we need/want/ any additional taxonomy people might need to filter things? or would 'Categories' be enough?

I think Categories are enough. 

> Then, down the road, it's very possible to create archives by specific usernames if we ever wanted to do that.

I would love to see this.

**Comment by ryanwelcher** [comment]
I've create a PR to introduce this CPT and related items. I have also created #71 to allow us to control the query changes we need via a plugin rather than code.
