### ISSUE TITLE
Add a Menú with links to Developer Docs

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/wporg-developer-blog#7]
I would add a new Menú Section called **Developer Docs** with the following items 

- [Code Reference](https://developer.wordpress.org/reference/)
- [Coding Standards](https://developer.wordpress.org/coding-standards/)
- [Block Editor](https://developer.wordpress.org/coding-standards/)
- [Common APIs](https://developer.wordpress.org/apis/)
- [Themes](https://developer.wordpress.org/themes/)
- [Plugins](https://developer.wordpress.org/plugins/)
- [REST API](https://developer.wordpress.org/rest-api/)
- [WP-CLI](https://developer.wordpress.org/cli/commands/)

**Comment by bph** [comment]
That's done, @juanmaguitar 
<img width="731" alt="Screen Shot 2022-08-11 at 15 45 55" src="https://user-images.githubusercontent.com/39980/184148040-77edb566-5e78-487a-b2a5-61d4661541f9.png">
@ryelle this issue can be closed. :-)
