### ISSUE TITLE
Horizontal overflow in sidebar with search

### ISSUE THREAD

**Issue by justintadlock** [WordPress/wporg-developer-blog#72]
I just came across this when doing a search for `__experimentalDefaultControls` (no spaces between the characters), and it overflows the sidebar and over the content area:

![Image](https://github.com/user-attachments/assets/c7642e32-9d34-4e20-83ac-4c148867a30d)

**Comment by ryelle** [comment]
Would you want this to simply wrap, like below, or should the layout be switched to a full-width header? That would be a departure from the rest of the archive templates, but it would prevent this wrapping issue. 

![Image](https://github.com/user-attachments/assets/016336d7-00d8-4db6-a60b-34de6d57ed83)

**Comment by justintadlock** [comment]
Personally, I'd expect the text to break and just wrap as in your screenshot.

**Comment by ryelle** [comment]
I've added the CSS to wrap long search headings.
