### ISSUE TITLE
In CPT Snippet single post mentions don't link

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#73]
For our new snippets CPT, the mentions listed in the props section of a single post, don't link back to the WordPress profiles on the front end. 

Example post: [Snippet: Conditionally unregister patterns](https://developer.wordpress.org/news/snippets/conditionally-unregister-patterns/)
They seem to work in the Block editor, though. See screenshot  ![Image](https://github.com/user-attachments/assets/caac0db6-9077-465b-9526-07f8a3e94d6c)

Is there a way, that can be implemented? We might have a similar issue for the Video CPT.

**Comment by ryelle** [comment]
@bph I've enabled support, but you'll need to go back and re-save any existing content to parse out the mentions.

**Comment by bph** [comment]
@ryelle Thank you so much for taking care of it. It works now.
