### ISSUE TITLE
`<code>` elements nested in headings looks ugly

### ISSUE THREAD

**Issue by germanfrelo** [WordPress/wporg-developer-blog#74]
Example:

https://developer.wordpress.org/news/2022/12/07/leveraging-theme-json-and-per-block-styles-for-more-performant-themes/

![Screenshot of a page showing a 16px paragraph with a 14px inline code element, and below it a 29px heading with a word wrapped in a 14px code element](https://github.com/user-attachments/assets/f4d1e4e4-11e6-4c1e-9bb5-2156001d6d76)

In the CSS, `<code>` elements have a fixed font size of `14px`.

I suggest using a font size of `0.875em`. That way, when used in paragraphs (which have `16px`), it can keep the computed font size of `14px`, and also look good in headings:

![The same content from the previous screenshot, but with the browser's dev tools open, and a font size of 0.875em is added to the code elements](https://github.com/user-attachments/assets/c666ad4f-7611-488c-90bf-7ce31e49b17d)

**Comment by ryelle** [comment]
Thanks for the suggestion, I've updated this to `0.875em`.
