### ISSUE TITLE
Code Block: Missing Plugin? 

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#8]
From the test site, I copied [this article](https://developer.wordpress.org/test-site-test/2022/application-state-managed-withdispatch-withselect-and-compose-101/) and I ran into the "This block contains unexpected or invalid content" on the live site ([link to edit post page](https://developer.wordpress.org/news/wp-admin/post.php?post=10&action=edit))

![Screen Shot 2022-07-01 at 14 07 02](https://user-images.githubusercontent.com/39980/176948152-3c8660e5-71f2-49df-8923-04dfc54beb40.png)

It might be related to a missing plugin for the Code Syntax Block?

**Comment by ryelle** [comment]
Sorry, I didn't think to activate that plugin. Should be working now 👍🏻

**Comment by bph** [comment]
Thanks so much! Yes, it works.
